name = "tepasolutions"
main = "worker.js"
compatibility_date = "2024-01-01"

# Assets binding for static files (including SEO files)
# This should point to your build directory where SEO files are generated
[assets]
directory = "./build"
binding = "ASSETS"

# Environment variables for all environments
[vars]
# Supabase keys should be set via `wrangler secret put` instead of committed here
# VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY should be injected at runtime

# Production environment configuration
[env.production]

# Production-specific variables
[env.production.vars]
# SUPABASE_SERVICE_KEY should be set via `wrangler secret put SUPABASE_SERVICE_KEY` instead of committed here

# No routes needed - using Custom Domain in Cloudflare dashboard
# Configure Custom Domain: Workers & Pages > tepasolutions > Settings > Custom Domains > Add tepasolutions.asia

# Security and performance headers
[[env.production.rules]]
type = "Header"
src = "/*"

[env.production.rules.headers]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff" 
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for static assets
[[env.production.rules]]
type = "Header"
src = "*.{js,css,png,jpg,jpeg,gif,ico,svg,woff,woff2}"

[env.production.rules.headers]
Cache-Control = "public, max-age=31536000, immutable"

# No cache for HTML files to ensure fresh content
[[env.production.rules]]
type = "Header"
src = "*.html"

[env.production.rules.headers]
Cache-Control = "no-cache, no-store, must-revalidate"