name = "tepasolutions"
main = "worker.js"
compatibility_date = "2024-01-01"

# Assets binding for static files (including SEO files)
[assets]
directory = "./build"
binding = "ASSETS"

# Environment variables for all environments
[vars]
VITE_SUPABASE_URL = "https://ruhsxjeiegdeshcnbuxy.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aHN4amVpZWdkZXNoY25idXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDczNDMsImV4cCI6MjA3MjU4MzM0M30.ua-Et2U4A0bRH0CSKA0Q6iT5YWvjSIi-_nPoeclay0U"

# Production environment configuration
[env.production]

# Production-specific variables
[env.production.vars]
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aHN4amVpZWdkZXNoY25idXh5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzAwNzM0MywiZXhwIjoyMDcyNTgzMzQzfQ.4iw-R_ov_uvgU3Bw2D1L3MNNi0ylAZpaFltIeKQdvXs"

# Custom domain routes
[[env.production.route]]
pattern = "tepasolutions.asia/*"
zone_id = "44f08db3ccbe99d82d123d3eb0f331b4"

[[env.production.route]]
pattern = "www.tepasolutions.asia/*" 
zone_id = "44f08db3ccbe99d82d123d3eb0f331b4"

# Security and performance headers
[[env.production.rules]]
type = "Header"
src = "/*"

[env.production.rules.headers]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff" 
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache headers for static assets
[[env.production.rules]]
type = "Header"
src = "*.{js,css,png,jpg,jpeg,gif,ico,svg,woff,woff2}"

[env.production.rules.headers]
Cache-Control = "public, max-age=31536000, immutable"

# Development environment (optional)
[env.development]
routes = [
    { pattern = "tepasolutions-dev.pages.dev/*" }
]