name = "tepasolutions"
main = "./worker.js"
compatibility_date = "2024-01-01"

# Assets binding for static files
[assets]
directory = "./build"
binding = "ASSETS"

[vars]
VITE_SUPABASE_URL = "https://ruhsxjeiegdeshcnbuxy.supabase.co"
VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aHN4amVpZWdkZXNoY25idXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDczNDMsImV4cCI6MjA3MjU4MzM0M30.ua-Et2U4A0bRH0CSKA0Q6iT5YWvjSIi-_nPoeclay0U"

[env.production.vars]
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1aHN4amVpZWdkZXNoY25idXh5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzAwNzM0MywiZXhwIjoyMDcyNTgzMzQzfQ.4iw-R_ov_uvgU3Bw2D1L3MNNi0ylAZpaFltIeKQdvXs"

# Custom domain (uncomment when ready to use)
# [env.production]
# route = "tepasolutions.com/*"