// SEO data for dynamic content: articles, events, and career pages
// This file is auto-generated by seo-transform.ts - do not edit manually
import type { SEOData } from './seo-generator'

// Article SEO data (keyed by slug)
export const articleSeoData: Record<string, Omit<SEOData, 'canonical' | 'ogImage' | 'twitterImage'>> = {
  "iphone-17-review-philippines-pricing-release": {
    title: 'iPhone 17 Review: Philippines Pricing and Release Date Revealed | Tepa Solutions Blog',
    description: 'Everything you need to know about Apple\'s latest iPhone 17',
    keywords: [
      "iPhone 17",
      "Apple",
      "Philippines",
      "Review",
      "Mobile Technology",
      "tepa solutions",
      "tech insights",
      "digital transformation"
    ],
    ogTitle: 'iPhone 17 Review: Philippines Pricing and Release Date Revealed',
    ogDescription: 'Everything you need to know about Apple\'s latest iPhone 17',
    twitterTitle: 'iPhone 17 Review: Philippines Pricing and Release Date Revealed',
    twitterDescription: 'Everything you need to know about Apple\'s latest iPhone 17',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Article',
      headline: 'iPhone 17 Review: Philippines Pricing and Release Date Revealed',
      description: 'Everything you need to know about Apple\'s latest iPhone 17',
      author: {
        "@type": 'Person',
        name: 'Jake Martinez'
      },
      publisher: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        logo: {
          "@type": 'ImageObject',
          url: 'https://tepasolutions.asia/logo.png'
        }
      },
      datePublished: '2025-01-20',
      dateModified: '2025-01-20',
      mainEntityOfPage: {
        "@type": 'WebPage',
        "@id": 'https://tepasolutions.asia/articles/iphone-17-review-philippines-pricing-release'
      }
    }
  },
  "quantum-chip-technology-breakthrough-2025": {
    title: 'Quantum Chip Revolution: The Future of Computing is Here | Tepa Solutions Blog',
    description: 'Explore the groundbreaking developments in quantum chip technology that are set to revolutionize computing',
    keywords: [
      "Quantum Computing",
      "Technology",
      "Innovation",
      "Future Tech",
      "tepa solutions",
      "tech insights",
      "digital transformation"
    ],
    ogTitle: 'Quantum Chip Revolution: The Future of Computing is Here',
    ogDescription: 'Explore the groundbreaking developments in quantum chip technology that are set to revolutionize computing',
    twitterTitle: 'Quantum Chip Revolution: The Future of Computing is Here',
    twitterDescription: 'Explore the groundbreaking developments in quantum chip technology that are set to revolutionize computing',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Article',
      headline: 'Quantum Chip Revolution: The Future of Computing is Here',
      description: 'Explore the groundbreaking developments in quantum chip technology that are set to revolutionize computing',
      author: {
        "@type": 'Person',
        name: 'Dr. Maria Santos'
      },
      publisher: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        logo: {
          "@type": 'ImageObject',
          url: 'https://tepasolutions.asia/logo.png'
        }
      },
      datePublished: '2025-01-18',
      dateModified: '2025-01-18',
      mainEntityOfPage: {
        "@type": 'WebPage',
        "@id": 'https://tepasolutions.asia/articles/quantum-chip-technology-breakthrough-2025'
      }
    }
  },
  "big-tech-news-2025-major-developments": {
    title: 'Big Tech News 2025: Major Developments Shaping the Industry | Tepa Solutions Blog',
    description: 'Stay updated with the latest major developments in the tech industry',
    keywords: [
      "Big Tech",
      "Industry News",
      "AI",
      "Regulation",
      "Innovation",
      "tepa solutions",
      "tech insights",
      "digital transformation"
    ],
    ogTitle: 'Big Tech News 2025: Major Developments Shaping the Industry',
    ogDescription: 'Stay updated with the latest major developments in the tech industry',
    twitterTitle: 'Big Tech News 2025: Major Developments Shaping the Industry',
    twitterDescription: 'Stay updated with the latest major developments in the tech industry',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Article',
      headline: 'Big Tech News 2025: Major Developments Shaping the Industry',
      description: 'Stay updated with the latest major developments in the tech industry',
      author: {
        "@type": 'Person',
        name: 'Manuel Rodriguez'
      },
      publisher: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        logo: {
          "@type": 'ImageObject',
          url: 'https://tepasolutions.asia/logo.png'
        }
      },
      datePublished: '2025-01-16',
      dateModified: '2025-01-16',
      mainEntityOfPage: {
        "@type": 'WebPage',
        "@id": 'https://tepasolutions.asia/articles/big-tech-news-2025-major-developments'
      }
    }
  },
  "top-10-ai-video-generation-tools-comparison-2025": {
    title: 'Top 10 AI Video Generation Tools: Complete Comparison Guide 2025 | Tepa Solutions Blog',
    description: 'Comprehensive comparison of the best AI video generation tools available in 2025. From features and pricing to use cases and limitations',
    keywords: [
      "AI Video",
      "Content Creation",
      "Tools Comparison",
      "Video Generation",
      "tepa solutions",
      "tech insights",
      "digital transformation"
    ],
    ogTitle: 'Top 10 AI Video Generation Tools: Complete Comparison Guide 2025',
    ogDescription: 'Comprehensive comparison of the best AI video generation tools available in 2025. From features and pricing to use cases and limitations',
    twitterTitle: 'Top 10 AI Video Generation Tools: Complete Comparison Guide 2025',
    twitterDescription: 'Comprehensive comparison of the best AI video generation tools available in 2025. From features and pricing to use cases and limitations',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Article',
      headline: 'Top 10 AI Video Generation Tools: Complete Comparison Guide 2025',
      description: 'Comprehensive comparison of the best AI video generation tools available in 2025. From features and pricing to use cases and limitations',
      author: {
        "@type": 'Person',
        name: 'Sarah Chen'
      },
      publisher: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        logo: {
          "@type": 'ImageObject',
          url: 'https://tepasolutions.asia/logo.png'
        }
      },
      datePublished: '2025-01-14',
      dateModified: '2025-01-14',
      mainEntityOfPage: {
        "@type": 'WebPage',
        "@id": 'https://tepasolutions.asia/articles/top-10-ai-video-generation-tools-comparison-2025'
      }
    }
  }
};

// Event SEO data (keyed by slug)
export const eventSeoData: Record<string, Omit<SEOData, 'canonical' | 'ogImage' | 'twitterImage'>> = {
  "free-introduction-roblox-game-development": {
    title: 'Free Introduction of Roblox Game Development | Tepa Solutions Events',
    description: 'Join our comprehensive workshop where you\'ll learn the fundamentals of Roblox game development using Roblox Studio and Lua scripting. Perfect for beginn...',
    keywords: [
      "workshop",
      "tech events Philippines",
      "tepa solutions",
      "learning",
      "workshop"
    ],
    ogTitle: 'Free Introduction of Roblox Game Development',
    ogDescription: 'Join our comprehensive workshop where you\'ll learn the fundamentals of Roblox game development using Roblox Studio and Lua scripting. Perfect for beginners and aspiring game developers!',
    twitterTitle: 'Free Introduction of Roblox Game Development',
    twitterDescription: 'Join our comprehensive workshop where you\'ll learn the fundamentals of Roblox game development using Roblox Studio and Lua scripting. Perfect for beginners and aspiring game developers!',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Event',
      name: 'Free Introduction of Roblox Game Development',
      description: 'Join our comprehensive workshop where you\'ll learn the fundamentals of Roblox game development using Roblox Studio and Lua scripting. Perfect for beginners and aspiring game developers!',
      startDate: '2025-09-27',
      organizer: {
        "@type": 'Organization',
        name: 'Tepa Solutions'
      },
      location: {
        "@type": 'Place',
        name: 'Zoom Meeting'
      }
    }
  },
  "introduction-to-html-and-css": {
    title: 'Introduction to HTML and CSS | Tepa Solutions Events',
    description: 'Learn the fundamentals of web development with HTML and CSS. Perfect for beginners who want to start their journey in web development and create beautiful',
    keywords: [
      "workshop",
      "tech events Philippines",
      "tepa solutions",
      "learning",
      "workshop"
    ],
    ogTitle: 'Introduction to HTML and CSS',
    ogDescription: 'Learn the fundamentals of web development with HTML and CSS. Perfect for beginners who want to start their journey in web development and create beautiful',
    twitterTitle: 'Introduction to HTML and CSS',
    twitterDescription: 'Learn the fundamentals of web development with HTML and CSS. Perfect for beginners who want to start their journey in web development and create beautiful',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Event',
      name: 'Introduction to HTML and CSS',
      description: 'Learn the fundamentals of web development with HTML and CSS. Perfect for beginners who want to start their journey in web development and create beautiful',
      startDate: '2025-09-20',
      organizer: {
        "@type": 'Organization',
        name: 'Tepa Solutions'
      },
      location: {
        "@type": 'Place',
        name: 'Zoom Meeting'
      }
    }
  },
  "introduction-to-website-funnel": {
    title: 'Introduction to Website Funnel | Tepa Solutions Events',
    description: 'Learn how to create effective website funnels that convert visitors into customers. Master the psychology and strategy behind high-converting sales funn...',
    keywords: [
      "workshop",
      "tech events Philippines",
      "tepa solutions",
      "learning",
      "workshop"
    ],
    ogTitle: 'Introduction to Website Funnel',
    ogDescription: 'Learn how to create effective website funnels that convert visitors into customers. Master the psychology and strategy behind high-converting sales funnels for your business.',
    twitterTitle: 'Introduction to Website Funnel',
    twitterDescription: 'Learn how to create effective website funnels that convert visitors into customers. Master the psychology and strategy behind high-converting sales funnels for your business.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'Event',
      name: 'Introduction to Website Funnel',
      description: 'Learn how to create effective website funnels that convert visitors into customers. Master the psychology and strategy behind high-converting sales funnels for your business.',
      startDate: 'Coming Soon',
      organizer: {
        "@type": 'Organization',
        name: 'Tepa Solutions'
      },
      location: {
        "@type": 'Place',
        name: 'Zoom Meeting'
      }
    }
  }
};

// Career/Job SEO data (keyed by slug)
export const careerSeoData: Record<string, Omit<SEOData, 'canonical' | 'ogImage' | 'twitterImage'>> = {
  "intern-frontend-developer": {
    title: 'Frontend Developer Intern | Tepa Solutions Careers',
    description: 'Join our development team as a frontend developer intern. Learn React',
    keywords: [
      "frontend developer intern",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "internship"
    ],
    ogTitle: 'Frontend Developer Intern - Join Tepa Solutions',
    ogDescription: 'Join our development team as a frontend developer intern. Learn React',
    twitterTitle: 'Frontend Developer Intern Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. \"Join our development team as a frontend developer intern. Learn React',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Frontend Developer Intern',
      description: 'Join our development team as a frontend developer intern. Learn React',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'INTERN',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "intern-backend-developer": {
    title: 'Backend Developer Intern | Tepa Solutions Careers',
    description: 'Learn backend development with Node.js',
    keywords: [
      "backend developer intern",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "internship"
    ],
    ogTitle: 'Backend Developer Intern - Join Tepa Solutions',
    ogDescription: 'Learn backend development with Node.js',
    twitterTitle: 'Backend Developer Intern Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. \"Learn backend development with Node.js',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Backend Developer Intern',
      description: 'Learn backend development with Node.js',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'INTERN',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "intern-article-writer": {
    title: 'Article Writer Intern | Tepa Solutions Careers',
    description: 'Create engaging content about technology',
    keywords: [
      "article writer intern",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "internship"
    ],
    ogTitle: 'Article Writer Intern - Join Tepa Solutions',
    ogDescription: 'Create engaging content about technology',
    twitterTitle: 'Article Writer Intern Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. \"Create engaging content about technology',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Article Writer Intern',
      description: 'Create engaging content about technology',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'INTERN',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "intern-seo-specialist": {
    title: 'SEO Specialist Intern | Tepa Solutions Careers',
    description: 'Learn search engine optimization and digital marketing strategies while helping improve our clients\' online visibility and search rankings.',
    keywords: [
      "seo specialist intern",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "internship"
    ],
    ogTitle: 'SEO Specialist Intern - Join Tepa Solutions',
    ogDescription: 'Learn search engine optimization and digital marketing strategies while helping improve our clients\' online visibility and search rankings.',
    twitterTitle: 'SEO Specialist Intern Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Learn search engine optimization and digital marketing strategies while helping improve our clients\' online visibility and search rankings.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'SEO Specialist Intern',
      description: 'Learn search engine optimization and digital marketing strategies while helping improve our clients\' online visibility and search rankings.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'INTERN',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "intern-admin-assistant": {
    title: 'Administrative Assistant Intern | Tepa Solutions Careers',
    description: 'Support daily operations and learn business administration while working with a dynamic tech company focused on automation and innovation.',
    keywords: [
      "administrative assistant intern",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "internship"
    ],
    ogTitle: 'Administrative Assistant Intern - Join Tepa Solutions',
    ogDescription: 'Support daily operations and learn business administration while working with a dynamic tech company focused on automation and innovation.',
    twitterTitle: 'Administrative Assistant Intern Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Support daily operations and learn business administration while working with a dynamic tech company focused on automation and innovation.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Administrative Assistant Intern',
      description: 'Support daily operations and learn business administration while working with a dynamic tech company focused on automation and innovation.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'INTERN',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "intern-business-development": {
    title: 'Business Development Intern | Tepa Solutions Careers',
    description: 'Learn business development and sales strategies while supporting client acquisition and relationship building for our technology solutions.',
    keywords: [
      "business development intern",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "internship"
    ],
    ogTitle: 'Business Development Intern - Join Tepa Solutions',
    ogDescription: 'Learn business development and sales strategies while supporting client acquisition and relationship building for our technology solutions.',
    twitterTitle: 'Business Development Intern Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Learn business development and sales strategies while supporting client acquisition and relationship building for our technology solutions.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Business Development Intern',
      description: 'Learn business development and sales strategies while supporting client acquisition and relationship building for our technology solutions.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'INTERN',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "contract-fullstack-developer": {
    title: 'Full Stack Developer | Tepa Solutions Careers',
    description: 'Work on end-to-end web application development using modern technologies. 6-12 month contract opportunity for experienced developers who enjoy both fron...',
    keywords: [
      "full stack developer",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "contract"
    ],
    ogTitle: 'Full Stack Developer - Join Tepa Solutions',
    ogDescription: 'Work on end-to-end web application development using modern technologies. 6-12 month contract opportunity for experienced developers who enjoy both frontend and backend challenges.',
    twitterTitle: 'Full Stack Developer Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Work on end-to-end web application development using modern technologies. 6-12 month contract opportunity for experienced developers who enjoy both frontend and backend challenges.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Full Stack Developer',
      description: 'Work on end-to-end web application development using modern technologies. 6-12 month contract opportunity for experienced developers who enjoy both frontend and backend challenges.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'FULL_TIME',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "contract-mobile-app-developer": {
    title: 'Mobile App Developer | Tepa Solutions Careers',
    description: 'Develop native and cross-platform mobile applications. 6-12 month contract for experienced mobile developers working on innovative business solutions.',
    keywords: [
      "mobile app developer",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "contract"
    ],
    ogTitle: 'Mobile App Developer - Join Tepa Solutions',
    ogDescription: 'Develop native and cross-platform mobile applications. 6-12 month contract for experienced mobile developers working on innovative business solutions.',
    twitterTitle: 'Mobile App Developer Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Develop native and cross-platform mobile applications. 6-12 month contract for experienced mobile developers working on innovative business solutions.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Mobile App Developer',
      description: 'Develop native and cross-platform mobile applications. 6-12 month contract for experienced mobile developers working on innovative business solutions.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'FULL_TIME',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "contract-android-developer": {
    title: 'Android Developer | Tepa Solutions Careers',
    description: 'Build native Android applications using Kotlin and modern Android development practices. 6-12 month contract opportunity for Android specialists.',
    keywords: [
      "android developer",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "contract"
    ],
    ogTitle: 'Android Developer - Join Tepa Solutions',
    ogDescription: 'Build native Android applications using Kotlin and modern Android development practices. 6-12 month contract opportunity for Android specialists.',
    twitterTitle: 'Android Developer Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Build native Android applications using Kotlin and modern Android development practices. 6-12 month contract opportunity for Android specialists.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Android Developer',
      description: 'Build native Android applications using Kotlin and modern Android development practices. 6-12 month contract opportunity for Android specialists.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'FULL_TIME',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "contract-ios-developer": {
    title: 'iOS Developer | Tepa Solutions Careers',
    description: 'Create native iOS applications using Swift and iOS development frameworks. 6-12 month contract for experienced iOS developers.',
    keywords: [
      "ios developer",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "contract"
    ],
    ogTitle: 'iOS Developer - Join Tepa Solutions',
    ogDescription: 'Create native iOS applications using Swift and iOS development frameworks. 6-12 month contract for experienced iOS developers.',
    twitterTitle: 'iOS Developer Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Create native iOS applications using Swift and iOS development frameworks. 6-12 month contract for experienced iOS developers.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'iOS Developer',
      description: 'Create native iOS applications using Swift and iOS development frameworks. 6-12 month contract for experienced iOS developers.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'FULL_TIME',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  },
  "contract-backend-developer": {
    title: 'Backend Developer | Tepa Solutions Careers',
    description: 'Build scalable backend systems and APIs for business automation solutions. 6-12 month contract opportunity for backend specialists.',
    keywords: [
      "backend developer",
      "jobs Philippines",
      "tepa solutions careers",
      "tech jobs",
      "contract"
    ],
    ogTitle: 'Backend Developer - Join Tepa Solutions',
    ogDescription: 'Build scalable backend systems and APIs for business automation solutions. 6-12 month contract opportunity for backend specialists.',
    twitterTitle: 'Backend Developer Position Available',
    twitterDescription: 'Join our team at Tepa Solutions. Build scalable backend systems and APIs for business automation solutions. 6-12 month contract opportunity for backend specialists.',
    robots: 'index, follow',
    jsonLd: {
      "@context": 'https://schema.org',
      "@type": 'JobPosting',
      title: 'Backend Developer',
      description: 'Build scalable backend systems and APIs for business automation solutions. 6-12 month contract opportunity for backend specialists.',
      hiringOrganization: {
        "@type": 'Organization',
        name: 'Tepa Solutions',
        sameAs: 'https://tepasolutions.asia'
      },
      jobLocation: {
        "@type": 'Place',
        address: {
          "@type": 'PostalAddress',
          addressCountry: 'PH',
          addressRegion: 'Remote'
        }
      },
      employmentType: 'FULL_TIME',
      workHours: 'Flexible',
      validThrough: '2025-12-17'
    }
  }
};


// Helper function to generate SEO data for any article
export function generateArticleSEO(slug: string, title: string, excerpt: string, author: string, publishDate: string, tags: string[]): Omit<SEOData, 'canonical' | 'ogImage' | 'twitterImage'> {
  return {
    title: `${title} | Tepa Solutions Blog`,
    description: excerpt.length > 155 ? excerpt.substring(0, 152) + '...' : excerpt,
    keywords: [...tags, 'tepa solutions', 'tech insights', 'digital transformation'],
    ogTitle: title,
    ogDescription: excerpt,
    twitterTitle: title,
    twitterDescription: excerpt,
    robots: 'index, follow',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Article',
      'headline': title,
      'description': excerpt,
      'author': {
        '@type': 'Person',
        'name': author
      },
      'publisher': {
        '@type': 'Organization',
        'name': 'Tepa Solutions',
        'logo': {
          '@type': 'ImageObject',
          'url': 'https://tepasolutions.asia/logo.png'
        }
      },
      'datePublished': publishDate,
      'dateModified': publishDate,
      'mainEntityOfPage': {
        '@type': 'WebPage',
        '@id': `https://tepasolutions.asia/articles/${slug}`
      }
    }
  }
}

// Helper function to generate SEO data for any event
export function generateEventSEO(slug: string, title: string, description: string, eventDate: string, location: string, eventType: string = 'workshop'): Omit<SEOData, 'canonical' | 'ogImage' | 'twitterImage'> {
  return {
    title: `${title} | Tepa Solutions Events`,
    description: description.length > 155 ? description.substring(0, 152) + '...' : description,
    keywords: [eventType, 'tech events Philippines', 'tepa solutions', 'learning', 'workshop'],
    ogTitle: title,
    ogDescription: description,
    twitterTitle: title,
    twitterDescription: description,
    robots: 'index, follow',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'Event',
      'name': title,
      'description': description,
      'startDate': eventDate,
      'organizer': {
        '@type': 'Organization',
        'name': 'Tepa Solutions'
      },
      'location': {
        '@type': 'Place',
        'name': location
      }
    }
  }
}

// Helper function to generate SEO data for any job posting
export function generateJobSEO(slug: string, title: string, description: string, employmentType: string = 'FULL_TIME', remote: boolean = false): Omit<SEOData, 'canonical' | 'ogImage' | 'twitterImage'> {
  const locationText = remote ? 'Remote/Philippines' : 'Philippines'
  
  return {
    title: `${title} | Tepa Solutions Careers`,
    description: description.length > 155 ? description.substring(0, 152) + '...' : description,
    keywords: [title.toLowerCase(), 'jobs Philippines', 'tepa solutions careers', 'tech jobs', employmentType.toLowerCase().replace('_', ' ')],
    ogTitle: `${title} - Join Tepa Solutions`,
    ogDescription: description,
    twitterTitle: `${title} Position Available`,
    twitterDescription: `Join our team at Tepa Solutions. ${description}`,
    robots: 'index, follow',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'JobPosting',
      'title': title,
      'description': description,
      'hiringOrganization': {
        '@type': 'Organization',
        'name': 'Tepa Solutions',
        'sameAs': 'https://tepasolutions.asia'
      },
      'jobLocation': {
        '@type': 'Place',
        'address': {
          '@type': 'PostalAddress',
          'addressCountry': 'PH',
          'addressRegion': locationText
        }
      },
      'employmentType': employmentType,
      'workHours': remote ? 'Flexible' : '9:00 AM - 6:00 PM'
    }
  }
}