name = "tepa-r2-image-server"
compatibility_date = "2024-09-25"
main = "supabase/functions/r2-image-server/index.ts"

[[r2_buckets]]
binding = "Tepa_Image"
bucket_name = "tepaimage"
preview_bucket_name = "tepaimage"

[env.production]
account_id = "84dba3ff5add506e1aa52c53bcca2234"

[env.development]
account_id = "84dba3ff5add506e1aa52c53bcca2234"

# Environment variables for the worker
[vars]
ENVIRONMENT = "production"

# Development configuration
[dev]
port = 8787
local_protocol = "http"

# Build configuration
[build]
command = "npm run build"

# Deployment configuration
[deploy]
compatibility_date = "2024-09-25"